# Generated by Django 5.2.14 on 2026-06-14 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("momo", "MTN Mobile Money"),
                    ("card", "Card (Paystack)"),
                    ("bank_transfer", "Bank Transfer"),
                    ("cash_on_delivery", "Cash on Delivery"),
                ],
                default="cash_on_delivery",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="produce",
            name="accepts_bank_transfer",
            field=models.BooleanField(default=False, help_text="Accept Bank Transfer"),
        ),
        migrations.AddField(
            model_name="produce",
            name="accepts_card",
            field=models.BooleanField(
                default=False, help_text="Accept Card via Paystack"
            ),
        ),
        migrations.AddField(
            model_name="produce",
            name="accepts_cod",
            field=models.BooleanField(
                default=True, help_text="Accept Cash on Delivery"
            ),
        ),
        migrations.AddField(
            model_name="produce",
            name="accepts_momo",
            field=models.BooleanField(
                default=True, help_text="Accept MTN Mobile Money"
            ),
        ),
        migrations.AddField(
            model_name="produce",
            name="contact_phone",
            field=models.CharField(
                blank=True,
                help_text="Phone number buyers can reach the seller on",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="produce",
            name="egg_size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("small", "Small"),
                    ("medium", "Medium"),
                    ("large", "Large"),
                    ("jumbo", "Jumbo"),
                ],
                help_text="Only applicable when produce_type is eggs",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="produce",
            name="produce_type",
            field=models.CharField(
                choices=[
                    ("broilers", "Broilers"),
                    ("eggs", "Eggs"),
                    ("layers", "Layer Birds"),
                    ("day_old", "Day-old Chicks"),
                    ("smoked", "Smoked Chicken"),
                    ("guinea_fowl", "Guinea Fowl"),
                    ("turkey", "Turkey"),
                    ("duck", "Duck"),
                    ("quail", "Quail"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
    ]
