# Generated by Django 5.2.14 on 2026-06-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0004_card_label_hubtel"),
    ]

    operations = [
        migrations.AddField(
            model_name="produce",
            name="accepts_hubtel_momo",
            field=models.BooleanField(
                default=False,
                help_text="Accept Mobile Money via Hubtel — MTN, Telecel, AirtelTigo",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("momo", "MTN Mobile Money (Direct)"),
                    ("hubtel_momo", "Mobile Money — Other Networks (Hubtel)"),
                    ("card", "Card (Hubtel)"),
                    ("bank_transfer", "Bank Transfer"),
                    ("cash_on_delivery", "Cash on Delivery"),
                ],
                default="cash_on_delivery",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="produce",
            name="accepts_momo",
            field=models.BooleanField(
                default=True, help_text="Accept MTN Mobile Money (Direct)"
            ),
        ),
    ]
