# Generated by Django 5.2.14 on 2026-06-14 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("farmer", "Farmer"),
                    ("investor", "Investor"),
                    ("consumer", "Consumer"),
                    ("monitoring_officer", "Monitoring Officer"),
                    ("admin", "Admin"),
                    ("vet", "Veterinarian"),
                    ("input_dealer", "Input Dealer"),
                ],
                default="farmer",
                max_length=20,
            ),
        ),
    ]
