# Generated by Django 5.2.14 on 2026-06-26 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_otpverification"),
        ("accounts", "0003_alter_user_language"),
    ]

    operations = []
