# Generated by Django 5.2.14 on 2026-06-26 11:11

import accounts.otp_models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("farmer", "Farmer"),
                    ("investor", "Investor"),
                    ("consumer", "Consumer"),
                    ("monitoring_officer", "Monitoring Officer"),
                    ("admin", "Admin"),
                    ("vet", "Veterinarian"),
                    ("input_dealer", "Input Dealer"),
                ],
                default="farmer",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="OTPVerification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("sms", "SMS"), ("email", "Email")], max_length=10
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        default=accounts.otp_models._generate_otp, max_length=6
                    ),
                ),
                ("is_used", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="otp_verifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "otp_verifications",
                "ordering": ["-created_at"],
            },
        ),
    ]
