# Generated by Django 5.2.14 on 2026-06-14 23:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farms", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="farmactivitylog",
            name="flock_count",
        ),
        migrations.AddField(
            model_name="farm",
            name="monitoring_officer",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "monitoring_officer"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_farms",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="farmactivitylog",
            name="birds_processed",
            field=models.PositiveIntegerField(
                default=0, help_text="Birds processed/slaughtered today"
            ),
        ),
        migrations.AddField(
            model_name="farmactivitylog",
            name="birds_received",
            field=models.PositiveIntegerField(
                default=0, help_text="Live birds received for processing"
            ),
        ),
        migrations.AddField(
            model_name="farmactivitylog",
            name="broiler_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="farmactivitylog",
            name="carcass_weight_kg",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Total dressed carcass weight (kg)",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="farmactivitylog",
            name="chicks_hatched",
            field=models.PositiveIntegerField(
                default=0, help_text="Chicks successfully hatched today"
            ),
        ),
        migrations.AddField(
            model_name="farmactivitylog",
            name="chicks_sold",
            field=models.PositiveIntegerField(
                default=0, help_text="Day-old chicks sold/dispatched today"
            ),
        ),
        migrations.AddField(
            model_name="farmactivitylog",
            name="cold_storage_units",
            field=models.PositiveIntegerField(
                default=0, help_text="Units moved to cold storage"
            ),
        ),
        migrations.AddField(
            model_name="farmactivitylog",
            name="day_old_chick_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="farmactivitylog",
            name="duck_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="farmactivitylog",
            name="eggs_in_incubation",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of eggs currently in incubator"
            ),
        ),
        migrations.AddField(
            model_name="farmactivitylog",
            name="eggs_set_today",
            field=models.PositiveIntegerField(
                default=0, help_text="Eggs placed in incubator today"
            ),
        ),
        migrations.AddField(
            model_name="farmactivitylog",
            name="geese_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="farmactivitylog",
            name="guinea_fowl_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="farmactivitylog",
            name="hatch_rejects",
            field=models.PositiveIntegerField(
                default=0, help_text="Unhatched / infertile eggs removed"
            ),
        ),
        migrations.AddField(
            model_name="farmactivitylog",
            name="layer_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="farmactivitylog",
            name="ostrich_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="farmactivitylog",
            name="turkey_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="farmactivitylog",
            name="units_packaged",
            field=models.PositiveIntegerField(
                default=0, help_text="Packaged units (portions, whole birds, etc.)"
            ),
        ),
        migrations.AlterField(
            model_name="farm",
            name="flock_type",
            field=models.CharField(
                choices=[
                    ("broilers", "Broilers"),
                    ("layers", "Layers"),
                    ("guinea_fowl", "Guinea Fowl"),
                    ("turkey", "Turkey"),
                    ("duck", "Duck"),
                    ("geese", "Geese"),
                    ("ostrich", "Ostrich"),
                    ("day_old_chicks", "Day-Old Chicks"),
                    ("hatchery", "Hatchery Only"),
                    ("poultry_and_hatchery", "Poultry + Hatchery"),
                    ("meat_processing", "Meat Processing Farm"),
                    ("mixed", "Mixed Poultry"),
                ],
                max_length=20,
            ),
        ),
    ]
