# Generated by Django 5.2.15 on 2026-06-17 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farms", "0002_remove_farmactivitylog_flock_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="farmactivitylog",
            name="local_cock_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Local breed cocks (roosters)"
            ),
        ),
        migrations.AddField(
            model_name="farmactivitylog",
            name="local_hen_count",
            field=models.PositiveIntegerField(default=0, help_text="Local breed hens"),
        ),
        migrations.AlterField(
            model_name="farm",
            name="flock_type",
            field=models.CharField(
                choices=[
                    ("broilers", "Broilers"),
                    ("layers", "Layers"),
                    ("guinea_fowl", "Guinea Fowl"),
                    ("turkey", "Turkey"),
                    ("duck", "Duck"),
                    ("geese", "Geese"),
                    ("ostrich", "Ostrich"),
                    ("local_birds", "Local Birds (Cocks & Hens)"),
                    ("day_old_chicks", "Day-Old Chicks"),
                    ("hatchery", "Hatchery Only"),
                    ("poultry_and_hatchery", "Poultry + Hatchery"),
                    ("meat_processing", "Meat Processing Farm"),
                    ("mixed", "Mixed Poultry"),
                ],
                max_length=20,
            ),
        ),
    ]
