# Generated by Django 5.2.14 on 2026-06-24 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farms", "0004_farmactivitylog_media"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farmactivitylog",
            name="media_captured_at",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp when the media was captured", null=True
            ),
        ),
        migrations.AlterField(
            model_name="farmactivitylog",
            name="media_type",
            field=models.CharField(
                blank=True,
                choices=[("image", "Image"), ("video", "Video")],
                default="",
                max_length=10,
            ),
        ),
    ]
