# Generated by Django 5.2.14 on 2026-06-14 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainingmodule",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
